
services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: docker-sandbox-selenium
    shm_size: 2gb
    platform: linux/amd64
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - SE_VNC_NO_PASSWORD=1
      - SE_SCREEN_WIDTH=1800
      - SE_SCREEN_HEIGHT=960
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    ports:
      - "4444:4444"
      - "7900:7900"
  
  novnc:
    image: javanile/novnc
    environment:
      - REMOTE_HOST=localhost
      - REMOTE_PORT=5900
    ports:
      - "8081:8081"
    links:
      - selenium

  ubuntu:
    build:
      context: .
      args:
        uid: ${USER_ID:-1000}
    container_name: docker-sandbox-ubuntu
    stdin_open: true
    tty: true
    volumes:
      - ./mercadolibre_test:/home/selenium/mercadolibre_test
    depends_on:
      - selenium
      - novnc